### ISSUE TITLE
Portal Vocabularies is listed in folder_contents

### ISSUE THREAD

**Issue by regebro** [collective/Products.ATVocabularyManager#7]
Portal vocabularies should never be listed in folder_contents, which it is on one site I have, where the default view for the root is folder_contents (yeah they want it like that, no I don't know why).

I should dig down into why it gets listed and try to fix that, this is a reminder to do so.

**Comment by tomgross** [comment]
Fixed in https://github.com/collective/Products.ATVocabularyManager/commit/2ccc3e37e5c66c717ed9824b85bb9c4d263b3cd7
